version: '3.9'

services:
  backend:
    build: .
    container_name: workout
    tty: true
    ports:
      - 1001:1000
    volumes:
      - .:/workout
  db:
    image: postgres:12.1
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data